version: "3.8"
name: cozy

services:
  # Database
  couchdb:
    image: couchdb:3.3
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./volumes/couchdb/data:/opt/couchdb/data
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "${COUCHDB_PROTOCOL}://${COUCHDB_USER}:${COUCHDB_PASSWORD}@${COUCHDB_HOST}:${COUCHDB_PORT}/_up",
        ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - dokploy-network

  # Cozy Stack
  stack:
    image: cozy/cozy-stack
    pull_policy: always
    restart: unless-stopped
    env_file: .env
    depends_on:
      - couchdb
    healthcheck:
      test: '[ "$(curl -fsSL http://localhost:8080/status | jq -r .status)" = "OK" ]'
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    volumes:
      - ./volumes/cozy-stack/data:/var/lib/cozy/data
      - ./volumes/cozy-stack/config:/etc/cozy/
      - ./files/cozy.yml:/etc/cozy/cozy.yml
    networks:
      - dokploy-network

  # Reverse Proxy
  caddy:
    image: caddy:2.7
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    depends_on:
      - stack
    volumes:
      - ./volumes/caddy/data:/data
      - ./volumes/caddy/etc:/etc/caddy
      - ./files/Caddyfile:/etc/caddy/Caddyfile
    expose:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    networks:
      - dokploy-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.caddy-app.rule=Host(`mycozy.ansicode.fr`)
      - traefik.http.routers.caddy-app.entrypoints=web
      - traefik.http.services.caddy-app.loadbalancer.server.port=80
      - traefik.http.services.caddy-app.loadbalancer.server.port=443

networks:
  dokploy-network:
    external: true